const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../public/phone.js'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'../public/features.js'),'utf8')+'\n'+fs.readFileSync(path.join(__dirname,'../public/app.js'),'utf8').replace(/init\(\);\s*$/,'');
function portalContext(pathname){const elements=new Map();const element=()=>({innerHTML:'',inert:false,focus(){},classList:{add(){},remove(){}}});const context=vm.createContext({libphonenumber:require('libphonenumber-js/max'),Intl,location:{pathname,hash:''},history:{replaceState(){}},document:{title:'',documentElement:{dataset:{theme:'light'}},body:{style:{}},querySelector(selector){if(selector==='.modal')return null;if(!elements.has(selector))elements.set(selector,element());return elements.get(selector);},addEventListener(){}},window:{addEventListener(){}},setTimeout(){},setInterval(){},clearTimeout(){},URL,console});vm.runInContext(source,context);return {run:code=>vm.runInContext(code,context),elements};}
test('Worker portal has worker navigation and registration without a role picker',()=>{const c=portalContext('/');const nav=c.run('header()');assert.match(nav,/Cari lowongan/);assert.match(nav,/Lamaran saya/);assert.doesNotMatch(nav,/Dashboard|Profil perusahaan/);c.run("auth('register')");const form=c.elements.get('#modal-root').innerHTML;assert.match(form,/Buat akun pencari kerja/);assert.match(form,/Nama lengkap/);assert.doesNotMatch(form,/type="radio"/);assert.match(form,/href="\/employer"/);});
test('Employer portal has dedicated landing, navigation and registration',()=>{const c=portalContext('/employer');assert.equal(c.run('homePage'),'dashboard');const nav=c.run('header()');assert.match(nav,/Dashboard/);assert.match(nav,/Perusahaan/);assert.doesNotMatch(nav,/Lamaran saya|Tersimpan/);c.run('render()');assert.match(c.elements.get('#app').innerHTML,/WORKEND EMPLOYER/);c.run("auth('register')");const form=c.elements.get('#modal-root').innerHTML;assert.match(form,/Nama penanggung jawab/);assert.match(form,/Daftar Employer/);assert.doesNotMatch(form,/type="radio"/);});
test('Cross-portal hash routes fall back to the correct portal home',()=>{const company=portalContext('/employer/');company.run("state.page='applications';render()");assert.equal(company.run('state.page'),'dashboard');const seeker=portalContext('/');seeker.run("state.page='dashboard';render()");assert.equal(seeker.run('state.page'),'jobs');});
test('Public feed refresh loads newly published company jobs without replacing an active form',async()=>{const c=portalContext('/');c.run("api=async()=>({jobs:[{id:'published',title:'Weekend crew',company:'Studio',location:'Bandung',city:'Bandung',pay:180000,day:'Sabtu',category:'Retail',color:'#eee',logo:'S',created:new Date().toISOString()}]})");await c.run('syncJobFeed()');assert.equal(c.run('state.jobs[0].id'),'published');assert.match(c.elements.get('#app').innerHTML,/Weekend crew/);c.run("document.activeElement={matches:()=>true};api=async()=>({jobs:[]})");await c.run('syncJobFeed()');assert.equal(c.run('state.jobs.length'),1);});
test('Unregistered Employer sees required business registration and cannot open the job form',()=>{const c=portalContext('/employer');c.run("state.user={name:'Employer Contact',role:'company',company:null};render()");const page=c.elements.get('#app').innerHTML;assert.match(page,/Lengkapi pendaftaran perusahaan/);for(const name of ['name','industry','city','address','email','phone','description'])assert.match(page,new RegExp('name="'+name+'"[^>]*required'));c.run('newJob()');assert.equal(c.run('location.hash'),'business');assert.ok(!c.elements.get('#modal-root')?.innerHTML.includes('id="job-form"'));});
test('Registered Employer can create jobs and edit business separately from personal profile',()=>{const c=portalContext('/employer');c.run("state.user={name:'Employer Contact',role:'company',company:{name:'Registered Business',business_type:'registered',employee_count:'1-10',address:'Jalan Melati nomor 10'}};render()");assert.match(c.elements.get('#app').innerHTML,/Halo, Registered Business/);c.run('newJob()');assert.match(c.elements.get('#modal-root').innerHTML,/id="job-form"/);assert.match(c.run('businessPage()'),/Simpan data perusahaan/);assert.match(c.run('profilePage()'),/Nama penanggung jawab/);});
test('Pay formatting preserves thousands and applies the Rp50.000 boundary',()=>{const c=portalContext('/employer');for(const value of ['50000','50.000'])assert.equal(c.run(`formatPay('${value}')`),'50.000');assert.equal(c.run("formatPay('150000')"),'150.000');c.run("payInput={value:'49.999',error:'',setCustomValidity(message){this.error=message}};validatePay(payInput)");assert.match(c.run('payInput.error'),/Rp50.000/);c.run("payInput.value='50.000';validatePay(payInput)");assert.equal(c.run('payInput.error'),'');});
test('Remote disables and hides only the onsite location fields',()=>{const c=portalContext('/employer');c.run("onsiteFields={};modeForm={elements:{work_mode:{value:'Remote'}},querySelector(){return onsiteFields}};updateWorkMode(modeForm)");assert.equal(c.run('onsiteFields.disabled'),true);assert.equal(c.run('onsiteFields.hidden'),true);c.run("modeForm.elements.work_mode.value='Onsite';updateWorkMode(modeForm)");assert.equal(c.run('onsiteFields.disabled'),false);assert.equal(c.run('onsiteFields.hidden'),false);});
test('Saved buttons in cards and details share pressed state and prominent saved class',()=>{const c=portalContext('/');c.run("state.saved=['saved-job']");for(const detail of [true,false]){const button=c.run(`savedButton('saved-job',${detail})`);assert.match(button,/saved/);assert.match(button,/aria-pressed="true"/);if(detail)assert.match(button,/>Tersimpan</);}c.run('state.saved=[]');assert.match(c.run("savedButton('saved-job',true)"),/aria-pressed="false"/);assert.match(c.run("savedButton('saved-job',true)"),/>Simpan</);});
test('Application form allows either CV field and leaves the other optional',()=>{const c=portalContext('/');c.run("state.user={role:'seeker'};state.jobs=[{id:'job',title:'Role',company:'Studio'}];applicationForm('job')");const html=c.elements.get('#modal-root').innerHTML;assert.match(html,/minimal salah satu/);assert.doesNotMatch(html,/<(?:textarea|input)[^>]*required/);assert.match(html,/name="portfolio"/);assert.match(html,/name="cv_file"/);assert.doesNotMatch(html,/cv_mode|hidden disabled/);});
test('Employer registration includes naming guidance and required employee count and office address',()=>{const c=portalContext('/employer');c.run("state.user={name:'Employer',role:'company'}");const html=c.run('businessPage()');assert.match(html,/sesuai yang tercantum di NPWP/);assert.match(html,/Instagram, Akun Seller Shopee/);assert.match(html,/nama toko Anda/);assert.match(html,/name="employee_count" required/);assert.match(html,/Solopreneur/);assert.match(html,/5001\+/);assert.match(html,/Alamat kantor lengkap/);assert.match(html,/<textarea[^>]*name="address"[^>]*required/);assert.doesNotMatch(html,/name="logo_file"[^>]*required/);});
test('Business naming guidance responds to the selected business category',()=>{const c=portalContext('/employer');c.run("nodes={};form={elements:{business_type:{value:'registered'},name:{}},querySelector(selector){return nodes[selector]||(nodes[selector]={})}};updateBusinessType(form)");assert.equal(c.run("nodes['#individual-name-help'].hidden"),true);assert.equal(c.run("nodes['#legal-name-help'].hidden"),false);assert.match(c.run('form.elements.name.placeholder'),/PT/);c.run("form.elements.business_type.value='individual';updateBusinessType(form)");assert.equal(c.run("nodes['#legal-name-help'].hidden"),true);assert.match(c.run('form.elements.name.placeholder'),/@tokosenja/);});
test('Uploaded logos render in worker job cards and details with initials as fallback',()=>{const c=portalContext('/');c.run("job={id:'job',title:'Weekend crew',company:'Studio',logo:'ST',color:'#eee',pay:150000,created:new Date().toISOString(),logo_url:'/api/companies/owner/logo?v=1'};state.jobs=[job]");assert.match(c.run('jobCard(job)'),/<img src="\/api\/companies\/owner\/logo\?v=1"/);c.run("detail('job')");assert.match(c.elements.get('#modal-root').innerHTML,/alt="Logo Studio"/);const fallback=c.run("companyLogo({company:'Studio',logo:'ST'})");assert.doesNotMatch(fallback,/<img/);assert.match(fallback,/>ST</);});
test('Legacy employers must complete newly required company fields before creating jobs',()=>{const c=portalContext('/employer');c.run("state.user={name:'Employer',role:'company',company:{name:'Legacy Company',address:'Jalan Melati 10'}};render()");assert.match(c.elements.get('#app').innerHTML,/Lengkapi pendaftaran perusahaan/);c.run('newJob()');assert.equal(c.run('location.hash'),'business');});


test('Radius filters onsite jobs by coordinates and excludes unlocated and remote jobs',()=>{
 const c=portalContext('/');c.run("state.searchLocation={latitude:-6.2,longitude:106.8};state.radius=5;state.jobs=[{id:'near',latitude:-6.21,longitude:106.8,work_mode:'Onsite',pay:100000},{id:'far',latitude:-6.4,longitude:106.8,work_mode:'Onsite',pay:100000},{id:'missing',pay:100000},{id:'remote',work_mode:'Remote',latitude:-6.2,longitude:106.8,pay:100000}]");
 assert.equal(c.run("filtered().map(j=>j.id).join(',')"),'near');c.run('state.radius=null');assert.equal(c.run('filtered().length'),4);
 assert.equal(c.run('haversine({latitude:0,longitude:0},{latitude:0,longitude:0})'),0);
 assert.ok(Math.abs(c.run('haversine({latitude:0,longitude:0},{latitude:0,longitude:1})')-111.195)<0.01);
});
test('Worker profile renders escaped experience, private photo and optional certificates',()=>{
 const c=portalContext('/');c.run("state.user={role:'seeker',name:'Candidate',email:'c@example.test',experience:'<script>alert(1)</script>',skills:'Latte art'}");const html=c.run('profilePage()');assert.match(html,/name="photo_file"/);assert.match(html,/name="certificates"/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>/);
});
test('Worker profile groups editable sections and marks only required fields with an asterisk',()=>{
 const c=portalContext('/');c.run("state.user={role:'seeker',name:'Candidate',email:'candidate@example.test'}");const html=c.run('profilePage()');
 for(const id of ['identity','about','experience','interests','skills','certificates'])assert.match(html,new RegExp('id="profile-'+id+'"'));
 assert.match(html,/Kelengkapan profil/);assert.match(html,/type="submit"/);
 assert.match(c.run("field('name','Nama','text','','required')"),/aria-label="Wajib diisi">\*<\/span>/);
 assert.doesNotMatch(c.run("field('headline','Judul profil')"),/required-label/);
});
test('Trust labels distinguish complete business data from unverified contact',()=>{
 const c=portalContext('/');const html=c.run('trustBadges({profile_complete:true,contact_verified:false})');assert.match(html,/Profil bisnis lengkap/);assert.match(html,/Kontak belum terverifikasi/);assert.doesNotMatch(html,/>Kontak terverifikasi</);
});
test('CV payload accepts link without file and rejects neither',async()=>{
 const c=portalContext('/');const result=await c.run("flexibleCvPayload({elements:{portfolio:{value:'https://example.test/cv'},cv_file:{files:[]}}})");assert.equal(result.portfolio,'https://example.test/cv');await assert.rejects(c.run("flexibleCvPayload({elements:{portfolio:{value:''},cv_file:{files:[]}}})"),/Cukup salah satu/);
});


test('Radius editing lives in the location modal and choosing a point does not apply early',()=>{
 const c=portalContext('/');assert.doesNotMatch(c.run('distanceFilter()'),/id="radius-km"/);c.run("state.searchLocation={latitude:-6.2,longitude:106.8,label:'Titik lama'};state.radius=15;locationPrompt()");
 const html=c.elements.get('#modal-root').innerHTML;assert.match(html,/id="radius-km"/);assert.match(html,/value="15"/);assert.match(html,/Terapkan lokasi/);
 c.run("pickedText={};results={};picker={dataset:{target:'worker'},closest(){return {querySelector(){return pickedText}}},querySelector(){return results}};setPickedLocation(picker,{latitude:-6.3,longitude:106.8,label:'Titik baru'})");assert.equal(c.run('state.searchLocation.label'),'Titik lama');assert.equal(c.run('state.radius'),15);assert.equal(c.run('workerLocationDraft.label'),'Titik baru');
});
test('Pre-login verification prompts for exactly six numeric digits and business dashboard has no OTP form',()=>{
 const c=portalContext('/employer');c.run("verificationPrompt({email:'owner@example.test',email_sent:true})");const html=c.elements.get('#modal-root').innerHTML;assert.match(html,/maxlength="6"/);assert.match(html,/pattern="\[0-9\]\{6\}"/);assert.match(html,/autocomplete="one-time-code"/);assert.match(html,/Verifikasi & masuk/);
 c.run("state.user={company:{profile_complete:true,contact_verified:true}}");assert.doesNotMatch(c.run('verificationPanel()'),/verification-form|verification-send/);
});


test('Employer profile offers a dedicated email change flow with password and six-digit confirmation',()=>{
 const c=portalContext('/employer');c.run("state.user={role:'company',name:'Employer',email:'old@example.test',bio:'',phone:''}");const page=c.run('profilePage()');assert.match(page,/data-action="change-email"/);assert.match(page,/name="email"[^>]*readonly/);assert.doesNotMatch(page,/name="email"[^>]*disabled/);
 c.run('emailChangePrompt()');let html=c.elements.get('#modal-root').innerHTML;assert.match(html,/Kata sandi saat ini/);assert.match(html,/name="password"[^>]*required/);
 c.run("state.user.email_change={email:'new@example.test'};emailChangePrompt()");html=c.elements.get('#modal-root').innerHTML;assert.match(html,/new@example.test/);assert.match(html,/maxlength="6"/);assert.match(html,/Batalkan perubahan/);
});


test('Phone input offers international country codes with Indonesia selected and SMS controls',()=>{
 const c=portalContext('/');const html=c.run("phoneFields({phone:'081234567890',phone_country:'ID'},'profile')");assert.match(html,/Indonesia \(\+62\)/);assert.match(html,/value="ID" selected/);assert.match(html,/\(\+65\)/);assert.match(html,/Kirim kode SMS/);assert.match(html,/value="81234567890"/);
 const verified=c.run("phoneFields({phone:'+6581234567',phone_country:'SG',phone_verified:true},'business',true)");assert.match(verified,/value="SG" selected/);assert.match(verified,/Nomor terverifikasi/);assert.match(verified,/data-action="phone-send"[^>]*disabled/);
});
